### PR TITLE
fix: glob detection not working with suffixes

### LINKED ISSUE #25: Unable to use this plugin from custom extensions (like .vue)
Seems that it is impossible to allow inclusions from specific file extensions (e.g. .vue) with the tsconfig's `included` parameter due to the following line [here](https://github.com/aleclarson/vite-tsconfig-paths/blob/master/src/index.ts#L133-L135) as it converts any custom extension glob into a one that will always match directories only, e.g. `./src/**/*.vue` will convert to `./src/**/*.vue/**`

Version: 3.3.10 (previously tested 3.2.1 where it worked as intended)
The plugin is initialized like this:
```
tsconfigPaths({
    extensions: ['.ts', '.tsx', '.js', '.jsx', '.json', '.vue'],
})
```

### PR DESCRIPTION
**Pull request by TrixterTheTux**
Closes #25

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -130,7 +130,7 @@ function compileGlob(glob: string) {
   if (!relativeImportRE.test(glob)) {
     glob = './' + glob
   }
-  if (!glob.endsWith('*') && !/\.[tj]sx?/.test(glob)) {
+  if (!glob.split('/').pop()?.includes('*')) {
```
Comment (aleclarson) [inline src/index.ts:133]: `.split` never produces an empty array, so we can use non-null assertion here

```suggestion
  if (!glob.split('/').pop()!.includes('*')) {
```

**Review by aleclarson — CHANGES_REQUESTED** [review]

**Comment by aleclarson** [comment]
Thanks!
